config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'site/index'
  get 'index', to: 'site#index'
  get 'home', to: 'site#index', as: 'home'
  get 'projects', to: 'site#projects', as: 'projects'
  get 'resume', to: 'site#resume', as: 'resume'
  root 'site#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
# frozen_string_literal: true

class SiteController < ApplicationController
  def index
  end
  def home
    render action: "index"
  end
  def resume
  end
end

app/helpers/site_helper.rb
# frozen_string_literal: true

module SiteHelper
end

app/helpers/welcome_controller_helper.rb
# frozen_string_literal: true

module WelcomeControllerHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#78ffbc">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- meta -->
    
    <!-- page meta -->
    <meta name="description" content="<%= yield(:description) %>" />
    <meta name="keywords" content="<%= yield(:keywords) %>" />

    <!-- favicon -->
    <%= render 'application/favicon' %>

    <!-- page info -->
    <%= yield :head %>
    <!-- facebook -->
    <!-- https://developers.facebook.com/docs/sharing/webmasters/ -->

    <!-- csrf -->
    <%= csrf_meta_tags %>

    <!-- css/js -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        color: black;
      }
      #navi-logo {
        display: block;
        max-width:50px;
        max-height:50px;
        width: auto;
        height: auto;
      }
      <!-- For background -->
      .background {
        background-color: transparent;
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
      }

      .core {
        max-width: 1152px;
        width: 1152px;
        margin: 0 auto;
        margin-top: 0px;
        margin-right: auto;
        margin-bottom: 0px;
        margin-left: auto;
        position: relative;
      }

      .major-section {
        padding: 3rem 1.5rem;
      }

      .navi-whole {
        min-height: 5rem;
      }
      .navi-left {
        display: inline-block;
        white-space: nowrap;
        float: left;
      }
  
      .navi-left > div {
        width: 300px;
        display: inline-block;
        float: left;
      }
      .navi-img {
        max-height: 4rem;
        height: 100%;
        width: auto;
      }
      
      .navi-right {
        white-space: nowrap;
        display: inline-block;
        float: right;
      }

      .navi-right > div {
        width: 300px;
        display: inline-block;
        align-items: center;
        float: right;
      }
      a {
        text-decoration: none;
        color: currentColor;
      }
      a:hover, a:focus {
        color: currentColor;
        text-decoration: underline;
        border-bottom-color: black;
      }
      .navi-link {
        display: inline-block;
        align-items: center;
        padding: 1rem 1rem;
      }
    </style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="page">
    <section id="top-section" class="major-section">
      <div id="header-core" class="core">
        <nav id="navi-whole" class="navi-whole">
          <div id="navi-logo" class="navi-left">
            <div id="brand" class="navi-link">
              <%= image_tag("git_prof_pic.png", :class => "navi-img") %>
            </div>
          </div>
          <div id="navi-list" class="navi-right">
            <li id="navi-home" class="navi-link">
              <%= link_to "Home", root_path %>
            </li>
            <li id="navi-tech" class="navi-link">
              <%= link_to "Projects", projects_path %> 
            </li>
            <li id="navi-resume" class="navi-link">
              <%= link_to "Resume", resume_path %>
            </li>
          </div>
        </nav>
      </div>
    </section>
    <section id="mid-section" class="major-body">
      <%= yield %>
    </section>
    <section id="bot-section" class="major-tail">
      
    </section>
  </body>
</html>

app/views/site/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% content_for :head do %>
      <title>danielshu</title>
    <% end %>
  </head>
  <body>
    <section class="core">
      <h1>site#index</h1>
      <p>Find me in app/views/site/index.html.erb.</p>
      <%= link_to "Resume", resume_path %>
    </section>
  </body>
</html>

app/views/site/projects.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% content_for :head do %>
      <title>danielshu_projects</title>
    <% end %>
  </head>
  <section class="core">
    <h1>site#projects</h1>
    <p>app/views/site/projects.html.erb.</p>
    <%= link_to "Resume", resume_path %>
  </section>
</html>

app/views/site/resume.html.erb
<!DOCTYPE html>
<html lang="en-US">
<!-- Daniel Shu's resume v2.3.5-->
<head>
  <% content_for :head do %>
    <title>danielshu_resume</title>
  <% end %>
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <% stylesheet_link_tag "normalize.css" %>
  <% stylesheet_link_tag "skeleton.css" %>
  <% stylesheet_link_tag "main.css" %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>
  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<br>
   <div class="container">
      <div class="row">
         <div class="eight columns">
            <h1>Daniel Shu</h1>
         </div>
         <div class=" four columns ">
            <br><i class="fa fa-phone "></i> <span class="smallerest">(619)892-6402</span>
            <br><i class="fa fa-envelope "></i> <span class="smallerest">danutenshu@gmail.com</span>
            <br><i class="fa fa-linkedin "></i> <span class="smallerest">linkedin.com/in/danutenshu </span>
         </div>
      </div>
   </div>

	<div class="container">
		<div class="row linebreak">
			<hr>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="two columns">
			 <b> <h7>Education</h7> </b>
			</div>
			<div class="ten columns smallerest">
			  California Polytechnic State University, San Luis Obispo<br>
			  Bachelor of Science, Computer Engineering <br>
			  June 2016
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row linebreaktop">
			<hr class="hr-small">
		</div>
   </div>

   <div class="container">
		<div class="two columns">
		<b> <h7>Technical Skills</h7> </b>
		</div>

  		<div class="ten columns smallerest">
  			<span>
            <b>Languages: </b> Java, C, C++, Python, Assembly, HTML/Javascript, Excel VBA, Chinese (Mandarin) <br>
            <b>Tools: </b> Git, GDB, Eclipse (Maven), JIRA, ConEmu, Vim, Wordpress, Apache2, CRON, Wireshark, tcpview, nmap, putty, WinSCP, Tomcat, Apache, Ruby on Rails<br>
            <b>OS: </b> Amazon Web Service, Ansible, Vagrant/VirtualBox/VMWare, Red Hat/RHEL, Ubuntu, Windows (7, 10, Server), Android<br>
            <b>Database: </b> MySQL, database creation, duplicates, sequencing, query optimization <br>
            <b>Networking: </b> Packet error, physical routing, port forwarding, network security<br>
               <li>
                  <span>Simulated server/client UDP that copied files to client and handled packet error </span>
               </li>
            <b>Operating Systems: </b> Memory management, processes/threads, parallel processing, shell scripting, pipes, deadlock <br>
               <li>
                  <span>Recreated transition lookaside buffer in C </span>
               </li>
               <li>
                  <span>LZW file compression </span>
               </li>
         </span>
  		</div>
  	</div>

   <div class="container">
      <div class="row linebreak">
        <hr classs="hr-small">
      </div>
   </div>

   <div class="container">
      <div class="row">
         <div class="two columns">
            <b><h7>Experience</h7></b>
         </div>
         <div class=" ten columns smallerest">
			<b>Systems Engineer for SPAWAR (San Diego, CA) <span style="float:right;"> Aug 2017 - Feb 2018</span> </b>
               <ul>
                  Automate tool deployment to VMs and maintain project AWS structure.
                  <li>
                     <span>Decided(with team) Ansible design and automated tool deployment</span>
                  </li>
                  <li>
                     <span>Deploy tools behind a proxy server linked to a web interface</span>
                  </li>
                  <li>
                     <span>AWS System Administrator and server lab support</span>
                  </li>
               </ul>
            <b>Web Developer at Polymerex Medical Corp (San Diego, CA) <span style="float:right;"> Jan 2016 - Aug 2017</span> </b>
               <ul>
                  Redesign company website for easier maintenance by non-technical staff.
                  <li>
                     <span>Troubleshoot issues with .NET/Microsoft Access CMS (content management system)</span>
                  </li>
                  <li>
                     <span>Migrate existing website from antiquated .NET CMS to modern WordPress CMS</span>
                  </li>
                  <li>
                     <span>Replace file-driven web server to database-driven LAMP web stack</span>
                  </li>
               </ul>
            <b>Researcher at Sunset Lab (San Luis Obispo, CA) <span style="float:right;"> Jun 2015 - Sep 2015</span> </b>
               <ul>
                  Write Python script to generate subtitles for videos of government meeting and increase accuracy identifying speakers.
                  <li>
                     <span>Automated processing jobs using CRON to identify speakers for un-subtitled videos </span>
                  </li>
                  <li >
                     <span>Improved speaker recognition accuracy via signal processing analysis by training models and tailoring associated variables in AGILE development cycles</span>
                  </li>
                  <li>
               <span>Extended research in senior project analyzing accuracy of open-source speaker recognition tools using sample from real-time database </span>
                  </li>
               </ul>
            <b>Intern at Polymerex Medical Corp  (San Diego, CA) <span style="float:right;"> Jun-Sep 2010-2014</span> </b>
               <ul class = "decreasemargin">
                  Re-invented balloon catheter production machine to use water- instead of air-cooling system using PLC (Mitsubishi, DirectLogic). Also produced five machines at $40K value each from less than $500 in parts
               </ul>
         </div>
      </div>
   </div>

   <br>
   
   <div class="container">
      <div class="row linebreak">
         <hr classs="hr-small">
      </div>
   </div>

   <div class="container">
      <div class="row">
	      <div class="two columns">
	         <b> <h7>Coursework & Projects</h7> </b>
	      </div>
	      <div class="ten columns smallerest">
            <span>
               <b>Artifical Intelligence: </b> Search algorithms (A*), neural networks, agents/environments <br>
               <b>Computer Design/Architecture: </b> HDL design on PLDs, CPU design, pipelines, input/output on multi-processors <br>
                  <li>
                     <span>Designed virtual CPU in VHDL on an FPGA board </span>
                  </li>
                  <li>
                     <span>Recreated SPIM simulator </span>
                  </li>
               <b>Embedded Systems: </b> Timing analysis (on oscilloscope), ADCs, sensors, transducers <br>
                  <li>
                     <span>Created sensor-based instrument using op-amps in circuit </span>
                  </li>
               <b>Data structure: </b> Abstract datatypes, trees/traversal, sorting algorithms, stacks/queues <br>
               <b>Circuit Design: </b> Semiconductors, logic circuits, diode/transistor application, AC steady state, RC/RL Circuits <br>
            </span>
            <ul>
               <br>
	         </ul>
	      </div>
      </div>
   </div>

<!-- End Document––––––––––––––––––––––––––––––––––––––––––––––––––-->
</body>
</html>